package SkillBasedDTOntology;

import java.net.URI;
import java.util.Collection;
import javax.xml.datatype.XMLGregorianCalendar;

import org.protege.owl.codegeneration.WrappedIndividual;

import org.semanticweb.owlapi.model.OWLNamedIndividual;
import org.semanticweb.owlapi.model.OWLOntology;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: Behavior <br>
 * @version generated on Mon Mar 27 14:26:55 CEST 2023 by au698550
 */

public interface Behavior extends WrappedIndividual {

    /* ***************************************************
     * Property http://www.semanticweb.org/ontologies/cooperativeDTs#hasEndpoint
     */
     
    /**
     * Gets all property values for the hasEndpoint property.<p>
     * 
     * @returns a collection of values for the hasEndpoint property.
     */
    Collection<? extends String> getHasEndpoint();

    /**
     * Checks if the class has a hasEndpoint property value.<p>
     * 
     * @return true if there is a hasEndpoint property value.
     */
    boolean hasHasEndpoint();

    /**
     * Adds a hasEndpoint property value.<p>
     * 
     * @param newHasEndpoint the hasEndpoint property value to be added
     */
    void addHasEndpoint(String newHasEndpoint);

    /**
     * Removes a hasEndpoint property value.<p>
     * 
     * @param oldHasEndpoint the hasEndpoint property value to be removed.
     */
    void removeHasEndpoint(String oldHasEndpoint);



    /* ***************************************************
     * Property http://www.semanticweb.org/ontologies/cooperativeDTs#hasFile
     */
     
    /**
     * Gets all property values for the hasFile property.<p>
     * 
     * @returns a collection of values for the hasFile property.
     */
    Collection<? extends String> getHasFile();

    /**
     * Checks if the class has a hasFile property value.<p>
     * 
     * @return true if there is a hasFile property value.
     */
    boolean hasHasFile();

    /**
     * Adds a hasFile property value.<p>
     * 
     * @param newHasFile the hasFile property value to be added
     */
    void addHasFile(String newHasFile);

    /**
     * Removes a hasFile property value.<p>
     * 
     * @param oldHasFile the hasFile property value to be removed.
     */
    void removeHasFile(String oldHasFile);



    /* ***************************************************
     * Property http://www.semanticweb.org/ontologies/cooperativeDTs#hasName
     */
     
    /**
     * Gets all property values for the hasName property.<p>
     * 
     * @returns a collection of values for the hasName property.
     */
    Collection<? extends String> getHasName();

    /**
     * Checks if the class has a hasName property value.<p>
     * 
     * @return true if there is a hasName property value.
     */
    boolean hasHasName();

    /**
     * Adds a hasName property value.<p>
     * 
     * @param newHasName the hasName property value to be added
     */
    void addHasName(String newHasName);

    /**
     * Removes a hasName property value.<p>
     * 
     * @param oldHasName the hasName property value to be removed.
     */
    void removeHasName(String oldHasName);



    /* ***************************************************
     * Common interfaces
     */

    OWLNamedIndividual getOwlIndividual();

    OWLOntology getOwlOntology();

    void delete();

}
